### ISSUE TITLE
Failed to install pros-editor on macOS

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-docs#131]
When trying to install `pros-editor` on macOS using `brew cask install pros-editor`, the installation fails with the output:
```
bradmacbook:~ bradmiller$ brew cask install pros-editor
==> Satisfying dependencies
==> Installing Formula dependencies: pros-cli
==> Installing purduesigbots/pros/pros-cli
==> Downloading https://github.com/purduesigbots/pros-cli/archive/3.1.4.tar.gz
Already downloaded: /Users/bradmiller/Library/Caches/Homebrew/downloads/45ba415fa2acd3405730a47efcd3b5f5f0527318ea903364427dd82eb548f0e6--pros-cli-3.1.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/53/c0/c7819f0bb2cf83e1b4b0d96c901b85191f598a7b534d297c2ef6dc80e2d3/virtualen
Already downloaded: /Users/bradmiller/Library/Caches/Homebrew/downloads/6d18e6ad1a4c8e31dfc412cb5513a676119ead57a6ad5c830a0ec57ac08fd763--virtualenv-16.6.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/pros-cli--homebrew-virtualenv-20190612-82487-11sxajw
Last 15 lines from /Users/bradmiller/Library/Logs/Homebrew/pros-cli/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/pros-cli--homebrew-virtualenv-20190612-82487-11sxajw/target
--install-scripts=/private/tmp/pros-cli--homebrew-virtualenv-20190612-82487-11sxajw/target/bin
--single-version-externally-managed
--record=installed.txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
Error: Failed executing: python3 -c import\ setuptools,\ tokenize
__file__\ =\ 'setup.py'
exec(compile(getattr(tokenize,\ 'open',\ open)(__file__).read()
\ \ .replace('\r\n',\ '\n'),\ __file__,\ 'exec'))
 --no-user-cfg install --prefix=/private/tmp/pros-cli--homebrew-virtualenv-20190612-82487-11sxajw/target --install-scripts=/private/tmp/pros-cli--homebrew-virtualenv-20190612-82487-11sxajw/target/bin --single-version-externally-managed --record=installed.txt
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1914:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1851:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1851:in `system'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:195:in `block in create'
/usr/local/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:190:in `create'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:114:in `virtualenv_create'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:162:in `virtualenv_install_with_resources'
/usr/local/Homebrew/Library/Taps/purduesigbots/homebrew-pros/Formula/pros-cli.rb:120:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:145:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1132:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2048:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2047:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2023:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1127:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:116:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:194:in `<main>'
```

**Comment by HotelCalifornia** [comment]
If you have a non-homebrew version of python installed, try installing `setuptools` with pip. Otherwise it might be best to just let Homebrew install python when the CLI formula runs
